### ISSUE TITLE
Crash con la misura della frequenza cardiaca

### ISSUE THREAD

**Issue by PorfirioTramontana** [matteocaiazzo/APPLICAZIONEESAME#5]
Sul mio telefono (Android 8), l'activity della misura della frequenza cardiaca va subito in crash.
Ecco il messaggio di errore.
Probabilmente dovete aggiungere qualche richiesta esplicita di servizio (fotocamera)

2019-06-06 13:07:57.203 26659-26659/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.androstock.myweatherapp, PID: 26659
    java.lang.RuntimeException: Unable to resume activity {com.androstock.myweatherapp/com.androstock.myweatherapp.BpmActivity}: java.lang.RuntimeException: Fail to connect to camera service
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3675)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3715)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1603)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6578)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:619)
        at android.hardware.Camera.open(Camera.java:445)
        at com.androstock.myweatherapp.BpmActivity.onResume(BpmActivity.java:101)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7120)

**Comment by matteocaiazzo** [comment]
Effettuato il push. Ora all'istallazione l'app richiede i permessi per la fotocamera e dopo averli concessi l'activity bpm non crasha piu

**Comment by PorfirioTramontana** [comment]
OK!
